//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace Nop.Payment.EasyPay
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "EasyPaySoap", Namespace = "http://easypay.by/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Array))]
    public partial class EasyPayService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback EP_CreateInvoiceOperationCompleted;

        private System.Threading.SendOrPostCallback EP_GetPaidInvoicesOperationCompleted;

        private System.Threading.SendOrPostCallback EP_GetPaidInvoicesExtOperationCompleted;

        private System.Threading.SendOrPostCallback EP_IsInvoicePaidOperationCompleted;

        private System.Threading.SendOrPostCallback EP_SendMessageOperationCompleted;

        private System.Threading.SendOrPostCallback EP_ConfirmInvoiceOperationCompleted;

        private System.Threading.SendOrPostCallback EP_CancelInvoiceOperationCompleted;

        private System.Threading.SendOrPostCallback EP_CreatePaymentOperationCompleted;

        private System.Threading.SendOrPostCallback EP_CheckPaymentOperationCompleted;

        private System.Threading.SendOrPostCallback EP_MerchantBalanceOperationCompleted;

        private System.Threading.SendOrPostCallback EP_CheckCardOperationCompleted;

        private System.Threading.SendOrPostCallback EP_CheckUserMoneyLimitOperationCompleted;

        private System.Threading.SendOrPostCallback EP_GetUserPhoneOperationCompleted;

        private System.Threading.SendOrPostCallback EP_StartBuyMoneyOperationCompleted;

        private System.Threading.SendOrPostCallback EP_FinishBuyMoneyOperationCompleted;

        private System.Threading.SendOrPostCallback EP_DecreaseInvoiceOperationCompleted;

        /// <remarks/>
        public EasyPayService(bool useSandbox)
        {
            this.Url = useSandbox ? "https://ssl.easypay.by/test/test.php" : "https://ssl.easypay.by/xml/server.php";
        }

        /// <remarks/>
        public event EP_CreateInvoiceCompletedEventHandler EP_CreateInvoiceCompleted;

        /// <remarks/>
        public event EP_GetPaidInvoicesCompletedEventHandler EP_GetPaidInvoicesCompleted;

        /// <remarks/>
        public event EP_GetPaidInvoicesExtCompletedEventHandler EP_GetPaidInvoicesExtCompleted;

        /// <remarks/>
        public event EP_IsInvoicePaidCompletedEventHandler EP_IsInvoicePaidCompleted;

        /// <remarks/>
        public event EP_SendMessageCompletedEventHandler EP_SendMessageCompleted;

        /// <remarks/>
        public event EP_ConfirmInvoiceCompletedEventHandler EP_ConfirmInvoiceCompleted;

        /// <remarks/>
        public event EP_CancelInvoiceCompletedEventHandler EP_CancelInvoiceCompleted;

        /// <remarks/>
        public event EP_CreatePaymentCompletedEventHandler EP_CreatePaymentCompleted;

        /// <remarks/>
        public event EP_CheckPaymentCompletedEventHandler EP_CheckPaymentCompleted;

        /// <remarks/>
        public event EP_MerchantBalanceCompletedEventHandler EP_MerchantBalanceCompleted;

        /// <remarks/>
        public event EP_CheckCardCompletedEventHandler EP_CheckCardCompleted;

        /// <remarks/>
        public event EP_CheckUserMoneyLimitCompletedEventHandler EP_CheckUserMoneyLimitCompleted;

        /// <remarks/>
        public event EP_GetUserPhoneCompletedEventHandler EP_GetUserPhoneCompleted;

        /// <remarks/>
        public event EP_StartBuyMoneyCompletedEventHandler EP_StartBuyMoneyCompleted;

        /// <remarks/>
        public event EP_FinishBuyMoneyCompletedEventHandler EP_FinishBuyMoneyCompleted;

        /// <remarks/>
        public event EP_DecreaseInvoiceCompletedEventHandler EP_DecreaseInvoiceCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_CreateInvoice", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_CreateInvoice(string mer_no, string pass, string order, decimal sum, int exp, string card, string comment, string info, string xml)
        {
            object[] results = this.Invoke("EP_CreateInvoice", new object[] {
                    mer_no,
                    pass,
                    order,
                    sum,
                    exp,
                    card,
                    comment,
                    info,
                    xml});
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_CreateInvoice(string mer_no, string pass, string order, decimal sum, int exp, string card, string comment, string info, string xml, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_CreateInvoice", new object[] {
                    mer_no,
                    pass,
                    order,
                    sum,
                    exp,
                    card,
                    comment,
                    info,
                    xml}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_CreateInvoice(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_CreateInvoiceAsync(string mer_no, string pass, string order, decimal sum, int exp, string card, string comment, string info, string xml)
        {
            this.EP_CreateInvoiceAsync(mer_no, pass, order, sum, exp, card, comment, info, xml, null);
        }

        /// <remarks/>
        public void EP_CreateInvoiceAsync(string mer_no, string pass, string order, decimal sum, int exp, string card, string comment, string info, string xml, object userState)
        {
            if ((this.EP_CreateInvoiceOperationCompleted == null))
            {
                this.EP_CreateInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_CreateInvoiceOperationCompleted);
            }
            this.InvokeAsync("EP_CreateInvoice", new object[] {
                    mer_no,
                    pass,
                    order,
                    sum,
                    exp,
                    card,
                    comment,
                    info,
                    xml}, this.EP_CreateInvoiceOperationCompleted, userState);
        }

        private void OnEP_CreateInvoiceOperationCompleted(object arg)
        {
            if ((this.EP_CreateInvoiceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_CreateInvoiceCompleted(this, new EP_CreateInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_GetPaidInvoices", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_GetPaidInvoices(string mer_no, string pass, string order, out Invoices invoices)
        {
            object[] results = this.Invoke("EP_GetPaidInvoices", new object[] {
                    mer_no,
                    pass,
                    order});
            invoices = ((Invoices)(results[1]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_GetPaidInvoices(string mer_no, string pass, string order, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_GetPaidInvoices", new object[] {
                    mer_no,
                    pass,
                    order}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_GetPaidInvoices(System.IAsyncResult asyncResult, out Invoices invoices)
        {
            object[] results = this.EndInvoke(asyncResult);
            invoices = ((Invoices)(results[1]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_GetPaidInvoicesAsync(string mer_no, string pass, string order)
        {
            this.EP_GetPaidInvoicesAsync(mer_no, pass, order, null);
        }

        /// <remarks/>
        public void EP_GetPaidInvoicesAsync(string mer_no, string pass, string order, object userState)
        {
            if ((this.EP_GetPaidInvoicesOperationCompleted == null))
            {
                this.EP_GetPaidInvoicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_GetPaidInvoicesOperationCompleted);
            }
            this.InvokeAsync("EP_GetPaidInvoices", new object[] {
                    mer_no,
                    pass,
                    order}, this.EP_GetPaidInvoicesOperationCompleted, userState);
        }

        private void OnEP_GetPaidInvoicesOperationCompleted(object arg)
        {
            if ((this.EP_GetPaidInvoicesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_GetPaidInvoicesCompleted(this, new EP_GetPaidInvoicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_GetPaidInvoicesExt", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_GetPaidInvoicesExt(string mer_no, string pass, string order, out InvoicesExt invoices_ext)
        {
            object[] results = this.Invoke("EP_GetPaidInvoicesExt", new object[] {
                    mer_no,
                    pass,
                    order});
            invoices_ext = ((InvoicesExt)(results[1]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_GetPaidInvoicesExt(string mer_no, string pass, string order, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_GetPaidInvoicesExt", new object[] {
                    mer_no,
                    pass,
                    order}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_GetPaidInvoicesExt(System.IAsyncResult asyncResult, out InvoicesExt invoices_ext)
        {
            object[] results = this.EndInvoke(asyncResult);
            invoices_ext = ((InvoicesExt)(results[1]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_GetPaidInvoicesExtAsync(string mer_no, string pass, string order)
        {
            this.EP_GetPaidInvoicesExtAsync(mer_no, pass, order, null);
        }

        /// <remarks/>
        public void EP_GetPaidInvoicesExtAsync(string mer_no, string pass, string order, object userState)
        {
            if ((this.EP_GetPaidInvoicesExtOperationCompleted == null))
            {
                this.EP_GetPaidInvoicesExtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_GetPaidInvoicesExtOperationCompleted);
            }
            this.InvokeAsync("EP_GetPaidInvoicesExt", new object[] {
                    mer_no,
                    pass,
                    order}, this.EP_GetPaidInvoicesExtOperationCompleted, userState);
        }

        private void OnEP_GetPaidInvoicesExtOperationCompleted(object arg)
        {
            if ((this.EP_GetPaidInvoicesExtCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_GetPaidInvoicesExtCompleted(this, new EP_GetPaidInvoicesExtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_IsInvoicePaid", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_IsInvoicePaid(string mer_no, string pass, string order)
        {
            object[] results = this.Invoke("EP_IsInvoicePaid", new object[] {
                    mer_no,
                    pass,
                    order});
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_IsInvoicePaid(string mer_no, string pass, string order, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_IsInvoicePaid", new object[] {
                    mer_no,
                    pass,
                    order}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_IsInvoicePaid(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_IsInvoicePaidAsync(string mer_no, string pass, string order)
        {
            this.EP_IsInvoicePaidAsync(mer_no, pass, order, null);
        }

        /// <remarks/>
        public void EP_IsInvoicePaidAsync(string mer_no, string pass, string order, object userState)
        {
            if ((this.EP_IsInvoicePaidOperationCompleted == null))
            {
                this.EP_IsInvoicePaidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_IsInvoicePaidOperationCompleted);
            }
            this.InvokeAsync("EP_IsInvoicePaid", new object[] {
                    mer_no,
                    pass,
                    order}, this.EP_IsInvoicePaidOperationCompleted, userState);
        }

        private void OnEP_IsInvoicePaidOperationCompleted(object arg)
        {
            if ((this.EP_IsInvoicePaidCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_IsInvoicePaidCompleted(this, new EP_IsInvoicePaidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_SendMessage", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_SendMessage(string mer_no, string pass, string order, string card, string subject, string text)
        {
            object[] results = this.Invoke("EP_SendMessage", new object[] {
                    mer_no,
                    pass,
                    order,
                    card,
                    subject,
                    text});
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_SendMessage(string mer_no, string pass, string order, string card, string subject, string text, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_SendMessage", new object[] {
                    mer_no,
                    pass,
                    order,
                    card,
                    subject,
                    text}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_SendMessage(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_SendMessageAsync(string mer_no, string pass, string order, string card, string subject, string text)
        {
            this.EP_SendMessageAsync(mer_no, pass, order, card, subject, text, null);
        }

        /// <remarks/>
        public void EP_SendMessageAsync(string mer_no, string pass, string order, string card, string subject, string text, object userState)
        {
            if ((this.EP_SendMessageOperationCompleted == null))
            {
                this.EP_SendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_SendMessageOperationCompleted);
            }
            this.InvokeAsync("EP_SendMessage", new object[] {
                    mer_no,
                    pass,
                    order,
                    card,
                    subject,
                    text}, this.EP_SendMessageOperationCompleted, userState);
        }

        private void OnEP_SendMessageOperationCompleted(object arg)
        {
            if ((this.EP_SendMessageCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_SendMessageCompleted(this, new EP_SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_ConfirmInvoice", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_ConfirmInvoice(string mer_no, string pass, string order)
        {
            object[] results = this.Invoke("EP_ConfirmInvoice", new object[] {
                    mer_no,
                    pass,
                    order});
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_ConfirmInvoice(string mer_no, string pass, string order, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_ConfirmInvoice", new object[] {
                    mer_no,
                    pass,
                    order}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_ConfirmInvoice(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_ConfirmInvoiceAsync(string mer_no, string pass, string order)
        {
            this.EP_ConfirmInvoiceAsync(mer_no, pass, order, null);
        }

        /// <remarks/>
        public void EP_ConfirmInvoiceAsync(string mer_no, string pass, string order, object userState)
        {
            if ((this.EP_ConfirmInvoiceOperationCompleted == null))
            {
                this.EP_ConfirmInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_ConfirmInvoiceOperationCompleted);
            }
            this.InvokeAsync("EP_ConfirmInvoice", new object[] {
                    mer_no,
                    pass,
                    order}, this.EP_ConfirmInvoiceOperationCompleted, userState);
        }

        private void OnEP_ConfirmInvoiceOperationCompleted(object arg)
        {
            if ((this.EP_ConfirmInvoiceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_ConfirmInvoiceCompleted(this, new EP_ConfirmInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_CancelInvoice", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_CancelInvoice(string mer_no, string pass, string order, string cancel_comment)
        {
            object[] results = this.Invoke("EP_CancelInvoice", new object[] {
                    mer_no,
                    pass,
                    order,
                    cancel_comment});
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_CancelInvoice(string mer_no, string pass, string order, string cancel_comment, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_CancelInvoice", new object[] {
                    mer_no,
                    pass,
                    order,
                    cancel_comment}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_CancelInvoice(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_CancelInvoiceAsync(string mer_no, string pass, string order, string cancel_comment)
        {
            this.EP_CancelInvoiceAsync(mer_no, pass, order, cancel_comment, null);
        }

        /// <remarks/>
        public void EP_CancelInvoiceAsync(string mer_no, string pass, string order, string cancel_comment, object userState)
        {
            if ((this.EP_CancelInvoiceOperationCompleted == null))
            {
                this.EP_CancelInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_CancelInvoiceOperationCompleted);
            }
            this.InvokeAsync("EP_CancelInvoice", new object[] {
                    mer_no,
                    pass,
                    order,
                    cancel_comment}, this.EP_CancelInvoiceOperationCompleted, userState);
        }

        private void OnEP_CancelInvoiceOperationCompleted(object arg)
        {
            if ((this.EP_CancelInvoiceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_CancelInvoiceCompleted(this, new EP_CancelInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_CreatePayment", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_CreatePayment(string mer_no, string pass, string pay_id, string card, decimal sum, string purpose, string xml)
        {
            object[] results = this.Invoke("EP_CreatePayment", new object[] {
                    mer_no,
                    pass,
                    pay_id,
                    card,
                    sum,
                    purpose,
                    xml});
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_CreatePayment(string mer_no, string pass, string pay_id, string card, decimal sum, string purpose, string xml, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_CreatePayment", new object[] {
                    mer_no,
                    pass,
                    pay_id,
                    card,
                    sum,
                    purpose,
                    xml}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_CreatePayment(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_CreatePaymentAsync(string mer_no, string pass, string pay_id, string card, decimal sum, string purpose, string xml)
        {
            this.EP_CreatePaymentAsync(mer_no, pass, pay_id, card, sum, purpose, xml, null);
        }

        /// <remarks/>
        public void EP_CreatePaymentAsync(string mer_no, string pass, string pay_id, string card, decimal sum, string purpose, string xml, object userState)
        {
            if ((this.EP_CreatePaymentOperationCompleted == null))
            {
                this.EP_CreatePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_CreatePaymentOperationCompleted);
            }
            this.InvokeAsync("EP_CreatePayment", new object[] {
                    mer_no,
                    pass,
                    pay_id,
                    card,
                    sum,
                    purpose,
                    xml}, this.EP_CreatePaymentOperationCompleted, userState);
        }

        private void OnEP_CreatePaymentOperationCompleted(object arg)
        {
            if ((this.EP_CreatePaymentCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_CreatePaymentCompleted(this, new EP_CreatePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_CheckPayment", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_CheckPayment(string mer_no, string pass, string pay_id)
        {
            object[] results = this.Invoke("EP_CheckPayment", new object[] {
                    mer_no,
                    pass,
                    pay_id});
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_CheckPayment(string mer_no, string pass, string pay_id, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_CheckPayment", new object[] {
                    mer_no,
                    pass,
                    pay_id}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_CheckPayment(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_CheckPaymentAsync(string mer_no, string pass, string pay_id)
        {
            this.EP_CheckPaymentAsync(mer_no, pass, pay_id, null);
        }

        /// <remarks/>
        public void EP_CheckPaymentAsync(string mer_no, string pass, string pay_id, object userState)
        {
            if ((this.EP_CheckPaymentOperationCompleted == null))
            {
                this.EP_CheckPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_CheckPaymentOperationCompleted);
            }
            this.InvokeAsync("EP_CheckPayment", new object[] {
                    mer_no,
                    pass,
                    pay_id}, this.EP_CheckPaymentOperationCompleted, userState);
        }

        private void OnEP_CheckPaymentOperationCompleted(object arg)
        {
            if ((this.EP_CheckPaymentCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_CheckPaymentCompleted(this, new EP_CheckPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_MerchantBalance", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_MerchantBalance(string mer_no, string pass, out string balance)
        {
            object[] results = this.Invoke("EP_MerchantBalance", new object[] {
                    mer_no,
                    pass});
            balance = ((string)(results[1]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_MerchantBalance(string mer_no, string pass, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_MerchantBalance", new object[] {
                    mer_no,
                    pass}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_MerchantBalance(System.IAsyncResult asyncResult, out string balance)
        {
            object[] results = this.EndInvoke(asyncResult);
            balance = ((string)(results[1]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_MerchantBalanceAsync(string mer_no, string pass)
        {
            this.EP_MerchantBalanceAsync(mer_no, pass, null);
        }

        /// <remarks/>
        public void EP_MerchantBalanceAsync(string mer_no, string pass, object userState)
        {
            if ((this.EP_MerchantBalanceOperationCompleted == null))
            {
                this.EP_MerchantBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_MerchantBalanceOperationCompleted);
            }
            this.InvokeAsync("EP_MerchantBalance", new object[] {
                    mer_no,
                    pass}, this.EP_MerchantBalanceOperationCompleted, userState);
        }

        private void OnEP_MerchantBalanceOperationCompleted(object arg)
        {
            if ((this.EP_MerchantBalanceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_MerchantBalanceCompleted(this, new EP_MerchantBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_CheckCard", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_CheckCard(string mer_no, string pass, string card)
        {
            object[] results = this.Invoke("EP_CheckCard", new object[] {
                    mer_no,
                    pass,
                    card});
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_CheckCard(string mer_no, string pass, string card, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_CheckCard", new object[] {
                    mer_no,
                    pass,
                    card}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_CheckCard(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_CheckCardAsync(string mer_no, string pass, string card)
        {
            this.EP_CheckCardAsync(mer_no, pass, card, null);
        }

        /// <remarks/>
        public void EP_CheckCardAsync(string mer_no, string pass, string card, object userState)
        {
            if ((this.EP_CheckCardOperationCompleted == null))
            {
                this.EP_CheckCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_CheckCardOperationCompleted);
            }
            this.InvokeAsync("EP_CheckCard", new object[] {
                    mer_no,
                    pass,
                    card}, this.EP_CheckCardOperationCompleted, userState);
        }

        private void OnEP_CheckCardOperationCompleted(object arg)
        {
            if ((this.EP_CheckCardCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_CheckCardCompleted(this, new EP_CheckCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_CheckUserMoneyLimit", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_CheckUserMoneyLimit(string mer_no, string pass, string card, decimal sum, string filter, out string permission_status, out string cur_money_limit)
        {
            object[] results = this.Invoke("EP_CheckUserMoneyLimit", new object[] {
                    mer_no,
                    pass,
                    card,
                    sum,
                    filter});
            permission_status = ((string)(results[1]));
            cur_money_limit = ((string)(results[2]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_CheckUserMoneyLimit(string mer_no, string pass, string card, decimal sum, string filter, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_CheckUserMoneyLimit", new object[] {
                    mer_no,
                    pass,
                    card,
                    sum,
                    filter}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_CheckUserMoneyLimit(System.IAsyncResult asyncResult, out string permission_status, out string cur_money_limit)
        {
            object[] results = this.EndInvoke(asyncResult);
            permission_status = ((string)(results[1]));
            cur_money_limit = ((string)(results[2]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_CheckUserMoneyLimitAsync(string mer_no, string pass, string card, decimal sum, string filter)
        {
            this.EP_CheckUserMoneyLimitAsync(mer_no, pass, card, sum, filter, null);
        }

        /// <remarks/>
        public void EP_CheckUserMoneyLimitAsync(string mer_no, string pass, string card, decimal sum, string filter, object userState)
        {
            if ((this.EP_CheckUserMoneyLimitOperationCompleted == null))
            {
                this.EP_CheckUserMoneyLimitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_CheckUserMoneyLimitOperationCompleted);
            }
            this.InvokeAsync("EP_CheckUserMoneyLimit", new object[] {
                    mer_no,
                    pass,
                    card,
                    sum,
                    filter}, this.EP_CheckUserMoneyLimitOperationCompleted, userState);
        }

        private void OnEP_CheckUserMoneyLimitOperationCompleted(object arg)
        {
            if ((this.EP_CheckUserMoneyLimitCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_CheckUserMoneyLimitCompleted(this, new EP_CheckUserMoneyLimitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_GetUserPhone", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_GetUserPhone(string mer_no, string pass, string transaction_id, out string phone, out string permission_status, out string card)
        {
            object[] results = this.Invoke("EP_GetUserPhone", new object[] {
                    mer_no,
                    pass,
                    transaction_id});
            phone = ((string)(results[1]));
            permission_status = ((string)(results[2]));
            card = ((string)(results[3]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_GetUserPhone(string mer_no, string pass, string transaction_id, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_GetUserPhone", new object[] {
                    mer_no,
                    pass,
                    transaction_id}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_GetUserPhone(System.IAsyncResult asyncResult, out string phone, out string permission_status, out string card)
        {
            object[] results = this.EndInvoke(asyncResult);
            phone = ((string)(results[1]));
            permission_status = ((string)(results[2]));
            card = ((string)(results[3]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_GetUserPhoneAsync(string mer_no, string pass, string transaction_id)
        {
            this.EP_GetUserPhoneAsync(mer_no, pass, transaction_id, null);
        }

        /// <remarks/>
        public void EP_GetUserPhoneAsync(string mer_no, string pass, string transaction_id, object userState)
        {
            if ((this.EP_GetUserPhoneOperationCompleted == null))
            {
                this.EP_GetUserPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_GetUserPhoneOperationCompleted);
            }
            this.InvokeAsync("EP_GetUserPhone", new object[] {
                    mer_no,
                    pass,
                    transaction_id}, this.EP_GetUserPhoneOperationCompleted, userState);
        }

        private void OnEP_GetUserPhoneOperationCompleted(object arg)
        {
            if ((this.EP_GetUserPhoneCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_GetUserPhoneCompleted(this, new EP_GetUserPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_StartBuyMoney", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_StartBuyMoney(string mer_no, string pass, string card, decimal sum, string order, string client_ip, out string phone, out string transaction_id)
        {
            object[] results = this.Invoke("EP_StartBuyMoney", new object[] {
                    mer_no,
                    pass,
                    card,
                    sum,
                    order,
                    client_ip});
            phone = ((string)(results[1]));
            transaction_id = ((string)(results[2]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_StartBuyMoney(string mer_no, string pass, string card, decimal sum, string order, string client_ip, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_StartBuyMoney", new object[] {
                    mer_no,
                    pass,
                    card,
                    sum,
                    order,
                    client_ip}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_StartBuyMoney(System.IAsyncResult asyncResult, out string phone, out string transaction_id)
        {
            object[] results = this.EndInvoke(asyncResult);
            phone = ((string)(results[1]));
            transaction_id = ((string)(results[2]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_StartBuyMoneyAsync(string mer_no, string pass, string card, decimal sum, string order, string client_ip)
        {
            this.EP_StartBuyMoneyAsync(mer_no, pass, card, sum, order, client_ip, null);
        }

        /// <remarks/>
        public void EP_StartBuyMoneyAsync(string mer_no, string pass, string card, decimal sum, string order, string client_ip, object userState)
        {
            if ((this.EP_StartBuyMoneyOperationCompleted == null))
            {
                this.EP_StartBuyMoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_StartBuyMoneyOperationCompleted);
            }
            this.InvokeAsync("EP_StartBuyMoney", new object[] {
                    mer_no,
                    pass,
                    card,
                    sum,
                    order,
                    client_ip}, this.EP_StartBuyMoneyOperationCompleted, userState);
        }

        private void OnEP_StartBuyMoneyOperationCompleted(object arg)
        {
            if ((this.EP_StartBuyMoneyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_StartBuyMoneyCompleted(this, new EP_StartBuyMoneyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_FinishBuyMoney", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_FinishBuyMoney(string mer_no, string pass, string transaction_id)
        {
            object[] results = this.Invoke("EP_FinishBuyMoney", new object[] {
                    mer_no,
                    pass,
                    transaction_id});
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_FinishBuyMoney(string mer_no, string pass, string transaction_id, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_FinishBuyMoney", new object[] {
                    mer_no,
                    pass,
                    transaction_id}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_FinishBuyMoney(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_FinishBuyMoneyAsync(string mer_no, string pass, string transaction_id)
        {
            this.EP_FinishBuyMoneyAsync(mer_no, pass, transaction_id, null);
        }

        /// <remarks/>
        public void EP_FinishBuyMoneyAsync(string mer_no, string pass, string transaction_id, object userState)
        {
            if ((this.EP_FinishBuyMoneyOperationCompleted == null))
            {
                this.EP_FinishBuyMoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_FinishBuyMoneyOperationCompleted);
            }
            this.InvokeAsync("EP_FinishBuyMoney", new object[] {
                    mer_no,
                    pass,
                    transaction_id}, this.EP_FinishBuyMoneyOperationCompleted, userState);
        }

        private void OnEP_FinishBuyMoneyOperationCompleted(object arg)
        {
            if ((this.EP_FinishBuyMoneyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_FinishBuyMoneyCompleted(this, new EP_FinishBuyMoneyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://easypay.by/EP_DecreaseInvoice", RequestNamespace = "http://easypay.by/", ResponseNamespace = "http://easypay.by/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("status")]
        public Status EP_DecreaseInvoice(string mer_no, string pass, string order, decimal sum)
        {
            object[] results = this.Invoke("EP_DecreaseInvoice", new object[] {
                    mer_no,
                    pass,
                    order,
                    sum});
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEP_DecreaseInvoice(string mer_no, string pass, string order, decimal sum, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EP_DecreaseInvoice", new object[] {
                    mer_no,
                    pass,
                    order,
                    sum}, callback, asyncState);
        }

        /// <remarks/>
        public Status EndEP_DecreaseInvoice(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void EP_DecreaseInvoiceAsync(string mer_no, string pass, string order, decimal sum)
        {
            this.EP_DecreaseInvoiceAsync(mer_no, pass, order, sum, null);
        }

        /// <remarks/>
        public void EP_DecreaseInvoiceAsync(string mer_no, string pass, string order, decimal sum, object userState)
        {
            if ((this.EP_DecreaseInvoiceOperationCompleted == null))
            {
                this.EP_DecreaseInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEP_DecreaseInvoiceOperationCompleted);
            }
            this.InvokeAsync("EP_DecreaseInvoice", new object[] {
                    mer_no,
                    pass,
                    order,
                    sum}, this.EP_DecreaseInvoiceOperationCompleted, userState);
        }

        private void OnEP_DecreaseInvoiceOperationCompleted(object arg)
        {
            if ((this.EP_DecreaseInvoiceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EP_DecreaseInvoiceCompleted(this, new EP_DecreaseInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://easypay.by/")]
    public partial class Status
    {

        private int codeField;

        private string messageField;

        /// <remarks/>
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvoicesExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Invoices))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.xmlsoap.org/soap/encoding/")]
    public partial class Array
    {

        private System.Xml.XmlElement[] anyField;

        private string arrayTypeField;

        private string offsetField;

        private bool offsetFieldSpecified;

        private string idField;

        private string hrefField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string arrayType
        {
            get
            {
                return this.arrayTypeField;
            }
            set
            {
                this.arrayTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string offset
        {
            get
            {
                return this.offsetField;
            }
            set
            {
                this.offsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offsetSpecified
        {
            get
            {
                return this.offsetFieldSpecified;
            }
            set
            {
                this.offsetFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://easypay.by/")]
    public partial class InvoicesExt : Array
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://easypay.by/")]
    public partial class Invoices : Array
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_CreateInvoiceCompletedEventHandler(object sender, EP_CreateInvoiceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_CreateInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_CreateInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_GetPaidInvoicesCompletedEventHandler(object sender, EP_GetPaidInvoicesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_GetPaidInvoicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_GetPaidInvoicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }

        /// <remarks/>
        public Invoices invoices
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Invoices)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_GetPaidInvoicesExtCompletedEventHandler(object sender, EP_GetPaidInvoicesExtCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_GetPaidInvoicesExtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_GetPaidInvoicesExtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }

        /// <remarks/>
        public InvoicesExt invoices_ext
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((InvoicesExt)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_IsInvoicePaidCompletedEventHandler(object sender, EP_IsInvoicePaidCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_IsInvoicePaidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_IsInvoicePaidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_SendMessageCompletedEventHandler(object sender, EP_SendMessageCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_SendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_SendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_ConfirmInvoiceCompletedEventHandler(object sender, EP_ConfirmInvoiceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_ConfirmInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_ConfirmInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_CancelInvoiceCompletedEventHandler(object sender, EP_CancelInvoiceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_CancelInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_CancelInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_CreatePaymentCompletedEventHandler(object sender, EP_CreatePaymentCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_CreatePaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_CreatePaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_CheckPaymentCompletedEventHandler(object sender, EP_CheckPaymentCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_CheckPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_CheckPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_MerchantBalanceCompletedEventHandler(object sender, EP_MerchantBalanceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_MerchantBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_MerchantBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }

        /// <remarks/>
        public string balance
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_CheckCardCompletedEventHandler(object sender, EP_CheckCardCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_CheckCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_CheckCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_CheckUserMoneyLimitCompletedEventHandler(object sender, EP_CheckUserMoneyLimitCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_CheckUserMoneyLimitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_CheckUserMoneyLimitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }

        /// <remarks/>
        public string permission_status
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }

        /// <remarks/>
        public string cur_money_limit
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_GetUserPhoneCompletedEventHandler(object sender, EP_GetUserPhoneCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_GetUserPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_GetUserPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }

        /// <remarks/>
        public string phone
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }

        /// <remarks/>
        public string permission_status
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }

        /// <remarks/>
        public string card
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_StartBuyMoneyCompletedEventHandler(object sender, EP_StartBuyMoneyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_StartBuyMoneyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_StartBuyMoneyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }

        /// <remarks/>
        public string phone
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }

        /// <remarks/>
        public string transaction_id
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_FinishBuyMoneyCompletedEventHandler(object sender, EP_FinishBuyMoneyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_FinishBuyMoneyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_FinishBuyMoneyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EP_DecreaseInvoiceCompletedEventHandler(object sender, EP_DecreaseInvoiceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EP_DecreaseInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EP_DecreaseInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
    }
}